### ISSUE TITLE
Not working on Xcode 6.3.2

### ISSUE THREAD

**Issue by ghost** [adamontherun/xCodeGenerateDescriptionPlugin#15]
I didn't get it to work through Alcatraz nor manual installation.

**Comment by adamontherun** [comment]
Hi @arctouch-brunopinheiro , sorry your having trouble with it. 

I just double checked that the proper UUID A16FF353-8441-459E-A50C-B071F53F51B7 was included for 6.2

Haven't been able to reproduce this.

**Comment by adamontherun** [comment]
@arctouch-brunopinheiro this is fixed. thanks for the tip. https://github.com/adamontherun/xCodeGenerateDescriptionPlugin/commit/8da6190980bac3825f557f12de949489ff17f47d

**Comment by shineeth** [comment]
Took latest code from git, still not able to view "Make Description" In the edit menu. Also tried installing using Alcatraz, but the result was same. Attached screenshot. I am a first time user.
![screen shot 2015-05-26 at 2 43 54 pm](https://cloud.githubusercontent.com/assets/6231481/7809239/7a396942-03b6-11e5-9d3a-ca9801592ebd.png)

**Comment by adamontherun** [comment]
thx for checking @shineeth I've dug into it and can't figure out why this isn't working. sorry

**Comment by adamontherun** [comment]
Please try uninstalling and reinstalling using the Alcatraz Package manager. You should then see the command in the edit menu or be able to use the shortcut CTRL + p

**Comment by nverinaud** [comment]
Does not work for me neither, even after uninstalling and reinstalling... :(

**Comment by zgp123** [comment]
Does not work for me neither, even after uninstalling and reinstalling... :(

**Comment by ajjnix** [comment]
i push bugfix this problem, wait accept
